
export const categoriesData = [
    {
        title: 'Bãi Biển',
        image: require('../../assets/images/beach.jpg'),
        screen: 'Beach', 
    },
    {
        title: 'Leo Núi',
        image: require('../../assets/images/Mountain.jpg'),
        screen: 'Mountain',
    },
    {
        title: 'Cắm Trại',
        image: require('../../assets/images/camp.jpg'),
        screen: 'Camp',
    },
    {
        title: 'Khám Phá Rừng',
        image: require('../../assets/images/forest.jpg'),
        screen: 'Forest',
    },
    {
        title: 'Hoàng Hôn',
        image: require('../../assets/images/sunset.jpg'),
        screen: 'Sunset',
    },
    {
        title: 'Hiking',
        image: require('../../assets/images/hiking.jpg'),
        screen: 'Hiking',
    },
    {
        title: 'Đại Dương',
        image: require('../../assets/images/ocean.jpg'),
        screen: 'Ocean',
    },
    
]
export const destinationData = [
    {
        title: 'Lâu đài Osaka',
        category: 'Xem thêm',
        duration: '12 Ngày',
        distance: '400 KM',
        weather: '20 °C',
        price: 1200,
        shortDescription: "Lâu đài Osaka là một trong những công trình nổi tiếng nhất của Nhật Bản, nằm ở khu Chūō-ku, Osaka.",
        longDescription: "Lâu đài Osaka là một công trình nổi tiếng của Nhật Bản, đóng vai trò quan trọng trong việc thống nhất đất nước vào thế kỷ 16, trong thời kỳ Azuchi-Momoyama.",
        image: require('../../assets/images/lau-dai-osaka-2-2.jpg')
    },
    {
        title: 'Đền thờ đảo Itsukushima',
        category: 'Xem thêm',
        duration: '7 Ngày',
        distance: '450 KM',
        weather: '30 °C',
        price: 3000,
        shortDescription: "Đền Itsukushima là một trong những điểm thu hút khách du lịch phổ biến nhất của Nhật Bản.",
        longDescription: "Đền Itsukushima là một đền thờ Thần đạo nằm trên đảo Itsukushima, nổi tiếng với cổng torii 'nổi'. Đền nằm ở thành phố Hatsukaichi, Hiroshima, có thể đến bằng phà từ ga Miyajimaguchi.",
        image: require('../../assets/images/Dentho.jpg')
    },
    {
        title: 'Đỉnh Babusar',
        category: 'Xem thêm',
        duration: '5 Ngày',
        distance: '299 KM',
        weather: '14 °C',
        price: 1000,
        shortDescription: "Đỉnh Babusar là một đèo núi ở Pakistan, nằm ở phía bắc thung lũng Kaghan.",
        longDescription: "Đỉnh Babusar là một đèo núi nối thung lũng Kaghan với Chilas qua Quốc lộ Karakoram, và là điểm cao nhất trong thung lũng Kaghan có thể dễ dàng đến được bằng xe.",
        image: require('../../assets/images/babusar.jpg')
    },
    {
        title: 'Đền Todaiji',
        category: 'Xem thêm',
        duration: '20 Ngày',
        distance: '604 KM',
        weather: '34 °C',
        price: 400,
        shortDescription: "Todaiji là một trong những ngôi đền nổi tiếng và quan trọng nhất của Nhật Bản, nằm ở Nara.",
        longDescription: "Đền Todaiji là một quần thể đền Phật giáo từng là một trong bảy ngôi đền lớn của Nhật Bản, nằm tại thành phố Nara. Được thành lập vào năm 738, đền Todaiji chính thức mở cửa vào năm 752.",
        image: require('../../assets/images/todaji.jpg')
    },
    {
        title: 'Núi Phú Sĩ',
        category: 'Xem thêm',
        duration: '15 Ngày',
        distance: '620 KM',
        weather: '18 °C',
        price: 2200,
        shortDescription: "Núi Phú Sĩ là ngọn núi cao nhất ở Nhật Bản, nổi tiếng với hình nón đối xứng.",
        longDescription: "Núi Phú Sĩ là một ngọn núi lửa không hoạt động và là điểm đến phổ biến cho du khách cũng như các nhà leo núi.",
        image: require('../../assets/images/nuiphusi.jpg')
    },
    {
        title: 'Rừng trúc Kyoto',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '250 KM',
        weather: '22 °C',
        price: 1500,
        shortDescription: "Rừng trúc Kyoto là một khu rừng nổi tiếng ở Arashiyama, Kyoto, Nhật Bản.",
        longDescription: "Rừng trúc ở Arashiyama là một địa điểm yên tĩnh và kỳ ảo, thu hút nhiều du khách quanh năm.",
        image: require('../../assets/images/rungtruc.jpg')
    },
    {
        title: 'Taj Mahal',
        category: 'Đề xuất',
        duration: '8 Ngày',
        distance: '300 KM',
        weather: '25 °C',
        price: 5000,
        shortDescription: "Taj Mahal, một trong bảy kỳ quan mới của thế giới, là một lăng mộ bằng đá cẩm thạch trắng ở Ấn Độ.",
        longDescription: "Taj Mahal, một Di sản Thế giới của UNESCO, được xây dựng vào năm 1632 bởi hoàng đế Shah Jahan để tưởng nhớ vợ yêu Mumtaz Mahal.",
        image: require('../../assets/images/kham-pha-den-Taj-Mahal-an-do.jpg')
    },
    {
        title: 'Tượng Chúa Kitô Cứu Thế',
        category: 'Đề xuất',
        duration: '3 Ngày',
        distance: '200 KM',
        weather: '28 °C',
        price: 1200,
        shortDescription: "Tượng Chúa Kitô Cứu Thế là một bức tượng khổng lồ của Chúa Giêsu ở Rio de Janeiro, Brazil.",
        longDescription: "Tượng Chúa Kitô Cứu Thế cao 30 mét và là một biểu tượng của đạo Kitô giáo, cũng như là một trong những kỳ quan mới của thế giới.",
        image: require('../../assets/images/chuacuuthe.jpg')
    },
    {
        title: 'Tháp Eiffel',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '350 KM',
        weather: '18 °C',
        price: 2500,
        shortDescription: "Tháp Eiffel, biểu tượng văn hóa toàn cầu của Pháp, tọa lạc tại Paris.",
        longDescription: "Được xây dựng vào năm 1889, tháp Eiffel là một công trình bằng sắt và là một trong những điểm đến nổi tiếng nhất thế giới.",
        image: require('../../assets/images/thap.jpg')
    },
    {
        title: 'Vạn Lý Trường Thành',
        category: 'Đề xuất',
        duration: '12 Ngày',
        distance: '500 KM',
        weather: '15 °C',
        price: 3000,
        shortDescription: "Vạn Lý Trường Thành là một công trình cổ xưa trải dài ở phía bắc Trung Quốc.",
        longDescription: "Ban đầu được xây dựng để bảo vệ Trung Quốc khỏi các cuộc xâm lược, Vạn Lý Trường Thành dài hơn 21,000 km và là một Di sản Thế giới của UNESCO.",
        image: require('../../assets/images/vanly.png')
    },
    {
        title: 'Nhà hát Opera Sydney',
        category: 'Đề xuất',
        duration: '6 Ngày',
        distance: '600 KM',
        weather: '24 °C',
        price: 3500,
        shortDescription: "Nhà hát Opera Sydney là một trung tâm biểu diễn nghệ thuật nằm bên cảng Sydney.",
        longDescription: "Nhà hát Opera Sydney là một công trình kiến trúc nổi tiếng của thế kỷ 20 và tổ chức hơn 1,500 buổi biểu diễn mỗi năm, thu hút hàng triệu du khách.",
        image: require('../../assets/images/nhahat.png')
    },
    {
        title: 'Vịnh Hạ Long',
        category: 'Phổ biến',
        duration: '5 Ngày',
        distance: '180 KM',
        weather: '26 °C',
        price: 2000,
        shortDescription: "Vịnh Hạ Long, Di sản Thế giới UNESCO, nổi tiếng với hàng nghìn hòn đảo đá vôi và hang động kỳ thú.",
        longDescription: "Vịnh Hạ Long thuộc tỉnh Quảng Ninh, là một trong những điểm đến du lịch hàng đầu Việt Nam với khung cảnh thiên nhiên hùng vĩ và độc đáo.",
        image: require('../../assets/images/halong.jpg')
    },
    {
        title: 'Hội An',
        category: 'Phổ biến',
        duration: '3 Ngày',
        distance: '30 KM',
        weather: '27 °C',
        price: 1500,
        shortDescription: "Hội An là một thành phố cổ được UNESCO công nhận, nổi tiếng với kiến trúc cổ kính và văn hóa truyền thống.",
        longDescription: "Phố cổ Hội An nằm ở tỉnh Quảng Nam, là nơi giao thoa của các nền văn hóa và di sản, với những con đường đèn lồng lung linh về đêm.",
        image: require('../../assets/images/hoian.jpg')
    },
    {
        title: 'Sa Pa',
        category: 'Phổ biến',
        duration: '7 Ngày',
        distance: '350 KM',
        weather: '18 °C',
        price: 2200,
        shortDescription: "Sa Pa nổi tiếng với những ruộng bậc thang tuyệt đẹp và cảnh núi rừng hoang sơ.",
        longDescription: "Nằm ở tỉnh Lào Cai, Sa Pa là điểm đến lý tưởng cho những ai yêu thiên nhiên và muốn khám phá văn hóa của các dân tộc thiểu số.",
        image: require('../../assets/images/sapa.jpg')
    },
    {
        title: 'Đà Lạt',
        category: 'Phổ biến',
        duration: '4 Ngày',
        distance: '300 KM',
        weather: '20 °C',
        price: 1800,
        shortDescription: "Đà Lạt được mệnh danh là thành phố ngàn hoa, nổi tiếng với khí hậu mát mẻ quanh năm.",
        longDescription: "Đà Lạt, thuộc tỉnh Lâm Đồng, là một điểm đến hấp dẫn với cảnh quan thiên nhiên lãng mạn, các biệt thự cổ và vườn hoa đa dạng.",
        image: require('../../assets/images/dalat.jpg')
    },
    {
        title: 'Cần Thơ',
        category: 'Phổ biến',
        duration: '6 Ngày',
        distance: '200 KM',
        weather: '29 °C',
        price: 1700,
        shortDescription: "Cần Thơ là trung tâm văn hóa và du lịch của miền Tây Nam Bộ, nổi tiếng với chợ nổi Cái Răng.",
        longDescription: "Cần Thơ được biết đến với nét văn hóa sông nước độc đáo, những vườn cây ăn trái trù phú và con người hiền hòa, mến khách.",
        image: require('../../assets/images/cantho.jpg')
    },
    {
        title: 'Grand Canyon',
        category: 'Đề xuất',
        duration: '8 Ngày',
        distance: '400 KM',
        weather: '35 °C',
        price: 3000,
        shortDescription: "Grand Canyon, một trong những kỳ quan thiên nhiên của thế giới, nằm ở bang Arizona, Hoa Kỳ.",
        longDescription: "Grand Canyon là hẻm núi lớn với hệ thống địa chất độc đáo, nổi tiếng với cảnh quan hùng vĩ và màu sắc đa dạng của đá sa thạch.",
        image: require('../../assets/images/grandcanyon.jpg')
    },
    {
        title: 'Thành phố Dubai',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '800 KM',
        weather: '40 °C',
        price: 7000,
        shortDescription: "Dubai, thành phố hiện đại và giàu có nhất của UAE, nổi tiếng với các tòa nhà chọc trời và trung tâm mua sắm xa hoa.",
        longDescription: "Dubai là điểm đến du lịch với các công trình kiến trúc kỳ vĩ như Burj Khalifa và Palm Jumeirah, cùng nền văn hóa Trung Đông độc đáo.",
        image: require('../../assets/images/dubai.jpg')
    },
    {
        title: 'Santorini',
        category: 'Đề xuất',
        duration: '6 Ngày',
        distance: '150 KM',
        weather: '25 °C',
        price: 4500,
        shortDescription: "Santorini là một hòn đảo Hy Lạp nổi tiếng với các ngôi nhà trắng và biển xanh thăm thẳm.",
        longDescription: "Santorini là một điểm đến lý tưởng cho tuần trăng mật với cảnh hoàng hôn tuyệt đẹp và ẩm thực Hy Lạp hấp dẫn.",
        image: require('../../assets/images/santorini.jpg')
    },
    {
        title: 'Angkor Wat',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '200 KM',
        weather: '32 °C',
        price: 1800,
        shortDescription: "Angkor Wat là khu đền lớn nhất thế giới, nằm ở Siem Reap, Campuchia.",
        longDescription: "Được xây dựng từ thế kỷ 12, Angkor Wat là biểu tượng của Campuchia và một trong những kỳ quan kiến trúc cổ đại.",
        image: require('../../assets/images/angkorwat.jpg')
    },
    {
        title: 'Cung điện Buckingham',
        category: 'Đề xuất',
        duration: '2 Ngày',
        distance: '50 KM',
        weather: '20 °C',
        price: 1500,
        shortDescription: "Cung điện Buckingham là nơi ở chính thức của Nữ hoàng Anh tại London.",
        longDescription: "Cung điện Buckingham là một địa điểm nổi bật với kiến trúc hoàng gia và nghi thức đổi gác nổi tiếng.",
        image: require('../../assets/images/buckingham.jpg')
    },
    {
        title: 'Kim tự tháp Giza',
        category: 'Đề xuất',
        duration: '7 Ngày',
        distance: '450 KM',
        weather: '38 °C',
        price: 2500,
        shortDescription: "Kim tự tháp Giza là kỳ quan cổ đại duy nhất còn tồn tại trên thế giới.",
        longDescription: "Nằm ở Ai Cập, Kim tự tháp Giza cùng Tượng Nhân Sư đại diện cho văn minh cổ đại và kỹ thuật xây dựng kỳ diệu.",
        image: require('../../assets/images/giza.jpg')
    },
    {
        title: 'Quần đảo Maldives',
        category: 'Đề xuất',
        duration: '12 Ngày',
        distance: '1000 KM',
        weather: '30 °C',
        price: 8000,
        shortDescription: "Maldives là thiên đường nhiệt đới với biển xanh trong vắt và các khu resort sang trọng.",
        longDescription: "Quần đảo Maldives nổi tiếng với các bãi biển đẹp và dịch vụ du lịch đẳng cấp thế giới, là điểm đến lý tưởng cho nghỉ dưỡng.",
        image: require('../../assets/images/maldives.jpg')
    },
    {
        title: 'Thác Niagara',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '300 KM',
        weather: '22 °C',
        price: 2200,
        shortDescription: "Thác Niagara là một trong những thác nước nổi tiếng nhất thế giới, nằm giữa Mỹ và Canada.",
        longDescription: "Thác Niagara là một cảnh quan thiên nhiên tuyệt đẹp với lưu lượng nước mạnh mẽ, thu hút hàng triệu du khách mỗi năm.",
        image: require('../../assets/images/niagara.jpg')
    },
    {
        title: 'Quần đảo Galápagos',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '600 KM',
        weather: '28 °C',
        price: 6000,
        shortDescription: "Quần đảo Galápagos là nơi có hệ sinh thái độc đáo, nổi tiếng với các loài động vật hiếm.",
        longDescription: "Nằm ngoài khơi Ecuador, quần đảo Galápagos là nơi Charles Darwin phát triển thuyết tiến hóa.",
        image: require('../../assets/images/galapagos.jpg')
    },
    {
        title: 'Petra',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '300 KM',
        weather: '35 °C',
        price: 2000,
        shortDescription: "Petra, thành phố đá cổ đại nằm ở Jordan, là một trong những kỳ quan thế giới mới.",
        longDescription: "Petra là một công trình kiến trúc độc đáo được khắc từ đá, nổi tiếng với Hẻm Núi Siq và Đền Al-Khazneh.",
        image: require('../../assets/images/petra.jpg')
    },
    {
        title: 'Cầu Cổng Vàng',
        category: 'Đề xuất',
        duration: '3 Ngày',
        distance: '150 KM',
        weather: '18 °C',
        price: 1500,
        shortDescription: "Cầu Cổng Vàng là biểu tượng nổi tiếng của San Francisco, Hoa Kỳ.",
        longDescription: "Cầu Cổng Vàng bắc qua eo biển San Francisco, được xây dựng vào năm 1937 và là một trong những cây cầu được chụp ảnh nhiều nhất thế giới.",
        image: require('../../assets/images/goldengate.jpg')
    },
    {
        title: 'Đảo Bali',
        category: 'Đề xuất',
        duration: '8 Ngày',
        distance: '400 KM',
        weather: '28 °C',
        price: 3200,
        shortDescription: "Bali, hòn đảo thiên đường của Indonesia, nổi tiếng với các bãi biển và văn hóa độc đáo.",
        longDescription: "Bali mang đến trải nghiệm tuyệt vời với thiên nhiên hùng vĩ, các ngôi đền Hindu, và nền ẩm thực phong phú.",
        image: require('../../assets/images/bali.jpg')
    },
    {
        title: 'Vườn Quốc gia Yellowstone',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '500 KM',
        weather: '12 °C',
        price: 4000,
        shortDescription: "Yellowstone là vườn quốc gia đầu tiên trên thế giới, nổi tiếng với suối nước nóng và mạch nước phun.",
        longDescription: "Vườn Quốc gia Yellowstone nằm ở Hoa Kỳ, là nơi có hệ động thực vật đa dạng và các cảnh quan thiên nhiên ngoạn mục.",
        image: require('../../assets/images/yellowstone.jpg')
    },
    {
        title: 'Công viên Quốc gia Serengeti',
        category: 'Đề xuất',
        duration: '7 Ngày',
        distance: '300 KM',
        weather: '27 °C',
        price: 5000,
        shortDescription: "Serengeti là một trong những công viên quốc gia nổi tiếng nhất thế giới, nằm ở Tanzania.",
        longDescription: "Serengeti là nơi diễn ra cuộc di cư của hàng triệu loài động vật hoang dã, là thiên đường của những người yêu thiên nhiên.",
        image: require('../../assets/images/serengeti.jpg')
    },
    {
        title: 'Quảng trường Đỏ',
        category: 'Đề xuất',
        duration: '3 Ngày',
        distance: '50 KM',
        weather: '10 °C',
        price: 2000,
        shortDescription: "Quảng trường Đỏ là trung tâm văn hóa và lịch sử của Moscow, Nga.",
        longDescription: "Nổi bật với Nhà thờ Thánh Basil, Quảng trường Đỏ là biểu tượng không thể thiếu của nước Nga.",
        image: require('../../assets/images/redsquare.jpg')
    },
    {
        title: 'Thác Victoria',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '350 KM',
        weather: '30 °C',
        price: 3500,
        shortDescription: "Thác Victoria là một trong những thác nước lớn nhất thế giới, nằm giữa Zambia và Zimbabwe.",
        longDescription: "Được UNESCO công nhận là Di sản Thế giới, thác Victoria có cảnh quan hùng vĩ với dòng nước chảy mạnh mẽ.",
        image: require('../../assets/images/victoriafalls.jpg')
    },
    {
        title: 'Tháp Burj Khalifa',
        category: 'Đề xuất',
        duration: '2 Ngày',
        distance: '20 KM',
        weather: '38 °C',
        price: 1800,
        shortDescription: "Burj Khalifa là tòa nhà cao nhất thế giới, tọa lạc tại Dubai, UAE.",
        longDescription: "Burj Khalifa cao 828 mét, là biểu tượng của sự hiện đại và phát triển vượt bậc của thành phố Dubai.",
        image: require('../../assets/images/burjkhalifa.jpg')
    },
    {
        title: 'Lâu đài Neuschwanstein',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '300 KM',
        weather: '16 °C',
        price: 2200,
        shortDescription: "Lâu đài Neuschwanstein ở Đức là nguồn cảm hứng cho Lâu đài Cinderella của Disney.",
        longDescription: "Được xây dựng vào thế kỷ 19, Neuschwanstein là biểu tượng của kiến trúc lãng mạn và thu hút hàng triệu du khách mỗi năm.",
        image: require('../../assets/images/neuschwanstein.jpg')
    },
    {
        title: 'Thành phố Venice',
        category: 'Đề xuất',
        duration: '6 Ngày',
        distance: '250 KM',
        weather: '22 °C',
        price: 2700,
        shortDescription: "Venice, thành phố nổi trên nước của Ý, nổi tiếng với các con kênh và kiến trúc cổ kính.",
        longDescription: "Venice là một trong những điểm đến lãng mạn nhất thế giới, với trải nghiệm gondola độc đáo và ẩm thực Ý đặc sắc.",
        image: require('../../assets/images/venice.jpg')
    },
    {
        title: 'Hẻm núi Antelope',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '150 KM',
        weather: '30 °C',
        price: 2500,
        shortDescription: "Hẻm núi Antelope ở bang Arizona, Mỹ, nổi bật với những dải màu sắc ngoạn mục.",
        longDescription: "Hẻm núi Antelope là điểm đến lý tưởng cho nhiếp ảnh gia và những người yêu thiên nhiên với các khe đá tự nhiên tuyệt đẹp.",
        image: require('../../assets/images/antelope.jpg')
    },
    {
        title: 'Đảo Jeju',
        category: 'Đề xuất',
        duration: '7 Ngày',
        distance: '500 KM',
        weather: '22 °C',
        price: 3200,
        shortDescription: "Đảo Jeju, viên ngọc của Hàn Quốc, nổi tiếng với cảnh quan thiên nhiên đẹp như tranh vẽ.",
        longDescription: "Đảo Jeju là một điểm du lịch hàng đầu của Hàn Quốc với núi Hallasan, bãi biển cát trắng, và những cánh đồng hoa cải dầu vàng rực rỡ.",
        image: require('../../assets/images/jeju.jpg')
    },
    {
        title: 'Thành phố Marrakech',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '300 KM',
        weather: '28 °C',
        price: 2200,
        shortDescription: "Marrakech là thành phố cổ của Morocco, nổi tiếng với nền văn hóa và kiến trúc độc đáo.",
        longDescription: "Marrakech, với các khu chợ sôi động và kiến trúc đặc sắc, là nơi hội tụ văn hóa truyền thống và hiện đại của Morocco.",
        image: require('../../assets/images/marrakech.jpg')
    },
    {
        title: 'Quần đảo Seychelles',
        category: 'Đề xuất',
        duration: '12 Ngày',
        distance: '600 KM',
        weather: '30 °C',
        price: 7000,
        shortDescription: "Quần đảo Seychelles là thiên đường nhiệt đới nổi tiếng với bãi biển đẹp và thiên nhiên hoang sơ.",
        longDescription: "Seychelles gồm hơn 100 hòn đảo với hệ sinh thái phong phú, là điểm đến lý tưởng cho những ai yêu biển cả.",
        image: require('../../assets/images/seychelles.jpg')
    },
    {
        title: 'Thành phố Istanbul',
        category: 'Đề xuất',
        duration: '6 Ngày',
        distance: '450 KM',
        weather: '18 °C',
        price: 2400,
        shortDescription: "Istanbul, thành phố nằm giữa hai châu lục, nổi bật với lịch sử phong phú và kiến trúc độc đáo.",
        longDescription: "Istanbul là trung tâm văn hóa và lịch sử của Thổ Nhĩ Kỳ, nổi tiếng với nhà thờ Hagia Sophia và Cung điện Topkapi.",
        image: require('../../assets/images/istanbul.jpg')
    },
    {
        title: 'Vườn quốc gia Banff',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '700 KM',
        weather: '12 °C',
        price: 4000,
        shortDescription: "Vườn quốc gia Banff ở Canada là một thiên đường dành cho những người yêu thiên nhiên và hoạt động ngoài trời.",
        longDescription: "Banff nổi tiếng với các hồ nước xanh ngọc, đỉnh núi tuyết trắng và hệ động thực vật đa dạng.",
        image: require('../../assets/images/banff.jpg')
    },
    {
        title: 'Thành phố Kyoto',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '300 KM',
        weather: '20 °C',
        price: 2000,
        shortDescription: "Kyoto, cố đô của Nhật Bản, nổi tiếng với những ngôi đền cổ kính và vườn truyền thống.",
        longDescription: "Kyoto là trung tâm văn hóa của Nhật Bản với những di tích lịch sử như Chùa Vàng Kinkakuji và Rừng trúc Arashiyama.",
        image: require('../../assets/images/kyoto.jpg')
    },
    {
        title: 'Hẻm núi Grand Teton',
        category: 'Đề xuất',
        duration: '7 Ngày',
        distance: '500 KM',
        weather: '15 °C',
        price: 3500,
        shortDescription: "Grand Teton là một dãy núi đẹp ngoạn mục nằm ở bang Wyoming, Mỹ.",
        longDescription: "Grand Teton nổi bật với cảnh quan núi cao hùng vĩ, hệ sinh thái phong phú, và các hoạt động ngoài trời đa dạng.",
        image: require('../../assets/images/grandteton.jpg')
    },
    {
        title: 'Công viên quốc gia Kruger',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '600 KM',
        weather: '26 °C',
        price: 5000,
        shortDescription: "Kruger là một trong những công viên quốc gia lớn nhất châu Phi, nằm ở Nam Phi.",
        longDescription: "Kruger là nơi bảo tồn động vật hoang dã, với cơ hội chiêm ngưỡng 'Big Five' và phong cảnh thiên nhiên ấn tượng.",
        image: require('../../assets/images/kruger.jpg')
    },
    {
        title: 'Thành phố Florence',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '200 KM',
        weather: '24 °C',
        price: 2200,
        shortDescription: "Florence là cái nôi của thời kỳ Phục hưng, nổi tiếng với nghệ thuật và kiến trúc độc đáo.",
        longDescription: "Florence là nơi tọa lạc của các tác phẩm nổi tiếng như tượng David của Michelangelo và nhà thờ Santa Maria del Fiore.",
        image: require('../../assets/images/florence.jpg')
    },
    {
        title: 'Thành phố Prague',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '250 KM',
        weather: '16 °C',
        price: 2000,
        shortDescription: "Prague, thủ đô của Cộng hòa Séc, là một thành phố đẹp như cổ tích với kiến trúc thời trung cổ.",
        longDescription: "Prague nổi tiếng với Cầu Charles, Lâu đài Prague và khu phố cổ đầy sức hút.",
        image: require('../../assets/images/prague.jpg')
    },
    {
        title: 'Thành phố Amsterdam',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '200 KM',
        weather: '15 °C',
        price: 2400,
        shortDescription: "Amsterdam, thủ đô của Hà Lan, nổi tiếng với các kênh đào và lối sống thân thiện.",
        longDescription: "Amsterdam có các kênh đào lịch sử, Bảo tàng Van Gogh, và cuộc sống về đêm sôi động, là điểm đến lý tưởng cho du khách yêu nghệ thuật và khám phá.",
        image: require('../../assets/images/amsterdam.jpg')
    },
    {
        title: 'Vườn quốc gia Yosemite',
        category: 'Đề xuất',
        duration: '8 Ngày',
        distance: '400 KM',
        weather: '18 °C',
        price: 3800,
        shortDescription: "Yosemite là một trong những vườn quốc gia nổi tiếng nhất của Hoa Kỳ, nổi bật với thác nước và dãy núi đá.",
        longDescription: "Yosemite thu hút du khách bởi các thác nước hùng vĩ, Thung lũng Yosemite, và các điểm leo núi như El Capitan.",
        image: require('../../assets/images/yosemite.jpg')
    },
    {
        title: 'Thành phố Budapest',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '250 KM',
        weather: '20 °C',
        price: 2000,
        shortDescription: "Budapest, thủ đô của Hungary, được mệnh danh là 'Viên ngọc của Danube'.",
        longDescription: "Budapest là một thành phố với các nhà tắm nước nóng, Cầu Xích Széchenyi, và những khu phố lịch sử tuyệt đẹp.",
        image: require('../../assets/images/budapest.jpg')
    },
    {
        title: 'Thành phố Cairo',
        category: 'Đề xuất',
        duration: '7 Ngày',
        distance: '400 KM',
        weather: '35 °C',
        price: 2600,
        shortDescription: "Cairo là thủ đô của Ai Cập, nổi tiếng với Kim tự tháp và Bảo tàng Ai Cập.",
        longDescription: "Cairo là nơi giao thoa giữa lịch sử cổ đại và hiện đại, với các điểm tham quan như Khu phố cổ và Kim tự tháp Giza.",
        image: require('../../assets/images/cairo.jpg')
    },
    {
        title: 'Đảo Bora Bora',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '1000 KM',
        weather: '30 °C',
        price: 8500,
        shortDescription: "Bora Bora là một hòn đảo đẹp như tranh ở Polynesia thuộc Pháp.",
        longDescription: "Bora Bora là điểm đến nổi tiếng với các khu nghỉ dưỡng trên mặt nước, bãi biển cát trắng, và làn nước trong vắt.",
        image: require('../../assets/images/borabora.jpg')
    },
    {
        title: 'Thành phố Rio de Janeiro',
        category: 'Đề xuất',
        duration: '6 Ngày',
        distance: '500 KM',
        weather: '28 °C',
        price: 4500,
        shortDescription: "Rio de Janeiro, thành phố biểu tượng của Brazil, nổi tiếng với lễ hội Carnival và bức tượng Chúa Kitô Cứu Thế.",
        longDescription: "Rio de Janeiro là một thành phố sôi động với các bãi biển Copacabana, sân vận động Maracanã và cảnh quan núi Sugarloaf.",
        image: require('../../assets/images/rio.jpg')
    },
    {
        title: 'Vườn quốc gia Torres del Paine',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '700 KM',
        weather: '10 °C',
        price: 6000,
        shortDescription: "Torres del Paine ở Chile là một trong những vườn quốc gia đẹp nhất Nam Mỹ.",
        longDescription: "Torres del Paine có các hồ nước xanh ngọc, các dãy núi cao chót vót, và hệ động thực vật phong phú.",
        image: require('../../assets/images/torresdelpaine.jpg')
    },
    {
        title: 'Thành phố Quebec',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '300 KM',
        weather: '10 °C',
        price: 2200,
        shortDescription: "Quebec, thành phố cổ kính ở Canada, nổi tiếng với văn hóa Pháp và kiến trúc cổ.",
        longDescription: "Quebec thu hút du khách bởi các con phố lát đá, lâu đài Frontenac, và nền ẩm thực phong phú.",
        image: require('../../assets/images/quebec.jpg')
    },
    {
        title: 'Thung lũng Loire',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '250 KM',
        weather: '22 °C',
        price: 2000,
        shortDescription: "Thung lũng Loire ở Pháp là nơi tập trung nhiều lâu đài đẹp nhất châu Âu.",
        longDescription: "Thung lũng Loire là Di sản Thế giới của UNESCO, nổi tiếng với các vườn nho, lâu đài Chenonceau, và sông Loire thơ mộng.",
        image: require('../../assets/images/loirevalley.jpg')
    },
    {
        title: 'Thành phố Dubrovnik',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '200 KM',
        weather: '24 °C',
        price: 2500,
        shortDescription: "Dubrovnik, được mệnh danh là 'Hòn ngọc của biển Adriatic', là một thành phố đẹp như tranh ở Croatia.",
        longDescription: "Dubrovnik nổi tiếng với các bức tường thành cổ, phố cổ đẹp như cổ tích, và khung cảnh biển Adriatic tuyệt đẹp.",
        image: require('../../assets/images/dubrovnik.jpg')
    },
    {
        title: 'Thành phố Munich',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '250 KM',
        weather: '16 °C',
        price: 2200,
        shortDescription: "Munich, thủ phủ của bang Bavaria, Đức, nổi tiếng với văn hóa bia và lễ hội Oktoberfest.",
        longDescription: "Munich là một thành phố lịch sử với các điểm tham quan như Cung điện Nymphenburg, Marienplatz, và công viên Englischer Garten.",
        image: require('../../assets/images/munich.jpg')
    },
    {
        title: 'Cung điện Alhambra',
        category: 'Đề xuất',
        duration: '3 Ngày',
        distance: '200 KM',
        weather: '25 °C',
        price: 2000,
        shortDescription: "Cung điện Alhambra ở Tây Ban Nha là một kiệt tác kiến trúc Hồi giáo.",
        longDescription: "Nằm tại Granada, Alhambra là tổ hợp cung điện và pháo đài với những khu vườn và hoa văn trang trí tinh xảo.",
        image: require('../../assets/images/alhambra.jpg')
    },
    {
        title: 'Thành phố Sydney',
        category: 'Đề xuất',
        duration: '7 Ngày',
        distance: '800 KM',
        weather: '22 °C',
        price: 4500,
        shortDescription: "Sydney, thành phố lớn nhất nước Úc, nổi tiếng với Cảng Sydney và Nhà hát Opera.",
        longDescription: "Sydney là điểm đến lý tưởng với bãi biển Bondi, cầu Cảng Sydney, và cuộc sống đô thị sôi động.",
        image: require('../../assets/images/sydney.jpg')
    },
    {
        title: 'Thành phố Cape Town',
        category: 'Đề xuất',
        duration: '6 Ngày',
        distance: '600 KM',
        weather: '24 °C',
        price: 3700,
        shortDescription: "Cape Town, thành phố duyên dáng của Nam Phi, nổi tiếng với Núi Bàn và Bãi biển Camps Bay.",
        longDescription: "Cape Town là nơi giao thoa giữa thiên nhiên hùng vĩ và văn hóa đa dạng, với các điểm tham quan như Đảo Robben và Vườn Bách Thảo Kirstenbosch.",
        image: require('../../assets/images/capetown.jpg')
    },
    {
        title: 'Đảo Tasmania',
        category: 'Đề xuất',
        duration: '10 Ngày',
        distance: '1000 KM',
        weather: '20 °C',
        price: 6000,
        shortDescription: "Đảo Tasmania là một thiên đường hoang dã của Úc, nổi tiếng với phong cảnh và động vật bản địa.",
        longDescription: "Tasmania thu hút du khách với Công viên Quốc gia Freycinet, Núi Cradle, và các loài động vật như quỷ Tasmania.",
        image: require('../../assets/images/tasmania.jpg')
    },
    {
        title: 'Đảo Hawaii',
        category: 'Đề xuất',
        duration: '12 Ngày',
        distance: '1200 KM',
        weather: '28 °C',
        price: 7000,
        shortDescription: "Hawaii là một quần đảo ở Thái Bình Dương, nổi tiếng với bãi biển và văn hóa bản địa.",
        longDescription: "Hawaii mang đến trải nghiệm đa dạng với các núi lửa, bãi biển Waikiki, và nền ẩm thực phong phú.",
        image: require('../../assets/images/hawaii.jpg')
    },
    {
        title: 'Lâu đài Edinburgh',
        category: 'Đề xuất',
        duration: '3 Ngày',
        distance: '250 KM',
        weather: '12 °C',
        price: 2000,
        shortDescription: "Lâu đài Edinburgh là biểu tượng của thủ đô Scotland.",
        longDescription: "Lâu đài Edinburgh nằm trên đỉnh đồi Castle Rock, với lịch sử lâu đời và các buổi biểu diễn quân nhạc hàng năm.",
        image: require('../../assets/images/edinburgh.jpg')
    },
    {
        title: 'Vịnh Milford Sound',
        category: 'Đề xuất',
        duration: '7 Ngày',
        distance: '500 KM',
        weather: '14 °C',
        price: 4000,
        shortDescription: "Milford Sound là một trong những vịnh hẹp đẹp nhất thế giới, nằm ở New Zealand.",
        longDescription: "Milford Sound nổi tiếng với cảnh quan núi non hùng vĩ, thác nước, và hệ động thực vật phong phú.",
        image: require('../../assets/images/milfordsound.jpg')
    },
    {
        title: 'Thành phố Lisbon',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '200 KM',
        weather: '20 °C',
        price: 2400,
        shortDescription: "Lisbon, thủ đô của Bồ Đào Nha, nổi tiếng với kiến trúc gạch Azulejos và ẩm thực đặc sắc.",
        longDescription: "Lisbon mang đến trải nghiệm thú vị với Lâu đài São Jorge, tháp Belém, và những con phố đầy màu sắc.",
        image: require('../../assets/images/lisbon.jpg')
    },
    {
        title: 'Thành phố Vienna',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '300 KM',
        weather: '18 °C',
        price: 2800,
        shortDescription: "Vienna, thủ đô của Áo, nổi tiếng với âm nhạc cổ điển và kiến trúc hoàng gia.",
        longDescription: "Vienna là cái nôi của âm nhạc cổ điển với các nhà hát lớn như Nhà hát Opera Vienna và Cung điện Schönbrunn.",
        image: require('../../assets/images/vienna.jpg')
    },
    {
        title: 'Thành phố Oslo',
        category: 'Đề xuất',
        duration: '5 Ngày',
        distance: '400 KM',
        weather: '10 °C',
        price: 3000,
        shortDescription: "Oslo, thủ đô của Na Uy, là nơi hội tụ văn hóa Bắc Âu và thiên nhiên hoang sơ.",
        longDescription: "Oslo nổi bật với Nhà hát Opera Oslo, Công viên điêu khắc Vigeland, và các vịnh hẹp xung quanh.",
        image: require('../../assets/images/oslo.jpg')
    },
    {
        title: 'Đỉnh Everest',
        category: 'Đề xuất',
        duration: '20 Ngày',
        distance: '1200 KM',
        weather: '-20 °C',
        price: 10000,
        shortDescription: "Everest, ngọn núi cao nhất thế giới, là đích đến của những nhà leo núi ưa mạo hiểm.",
        longDescription: "Everest mang lại trải nghiệm không thể quên với những thách thức và khung cảnh thiên nhiên hùng vĩ.",
        image: require('../../assets/images/everest.jpg')
    },
    {
        title: 'Khu bảo tồn Amazon',
        category: 'Đề xuất',
        duration: '14 Ngày',
        distance: '800 KM',
        weather: '30 °C',
        price: 7500,
        shortDescription: "Amazon là khu bảo tồn rừng nhiệt đới lớn nhất thế giới.",
        longDescription: "Amazon là nơi có hệ sinh thái phong phú với vô số loài động thực vật quý hiếm.",
        image: require('../../assets/images/amazon.jpg')
    },
    {
        title: 'Vịnh San Francisco',
        category: 'Đề xuất',
        duration: '3 Ngày',
        distance: '150 KM',
        weather: '17 °C',
        price: 2200,
        shortDescription: "Vịnh San Francisco nổi tiếng với cầu Cổng Vàng và đảo Alcatraz.",
        longDescription: "Vịnh San Francisco là nơi giao thoa giữa thiên nhiên và đô thị, là điểm đến không thể bỏ qua ở California.",
        image: require('../../assets/images/sanfrancisco.jpg')
    },
    {
        title: 'Thành phố Bruges',
        category: 'Đề xuất',
        duration: '3 Ngày',
        distance: '100 KM',
        weather: '12 °C',
        price: 2100,
        shortDescription: "Bruges, thành phố cổ kính ở Bỉ, nổi bật với các con kênh và kiến trúc thời trung cổ.",
        longDescription: "Bruges thu hút du khách bởi các điểm tham quan như Quảng trường Markt, Tháp chuông Belfry, và các nhà hàng truyền thống.",
        image: require('../../assets/images/bruges.jpg')
    },
    {
        title: 'Thành phố Krakow',
        category: 'Đề xuất',
        duration: '4 Ngày',
        distance: '200 KM',
        weather: '14 °C',
        price: 2300,
        shortDescription: "Krakow, cố đô của Ba Lan, nổi tiếng với lịch sử và kiến trúc độc đáo.",
        longDescription: "Krakow là nơi tọa lạc của Lâu đài Wawel, Quảng trường Chính Rynek Glowny, và các hầm mỏ muối Wieliczka.",
        image: require('../../assets/images/krakow.jpg')
    },
    
]